name: Build and Package MCP-Sum

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Package MCP-Sum
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-x86, macos-arm, windows-latest]
        include:
          - os: macos-x86
            python: 3.12
            node_version: 24
            architecture: x86_64
            build_command: .venv/bin/nuitka --follow-imports --standalone --onefile server/main.py
          - os: macos-arm
            python: 3.12
            node_version: 24
            architecture: arm64
            build_command: .venv/bin/nuitka --follow-imports --standalone --onefile server/main.py
          - os: windows-latest
            python: 3.12
            node_version: 24
            architecture: x86_64
            build_command: .venv\\Scripts\\nuitka --follow-imports --standalone --onefile server/main.py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Run UV Sync
      run: uv sync

    - name: Build with Nuitka
      run: ${{ matrix.build_command }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install DXT
      run: npm install -g @anthropic-ai/dxt

    - name: Pack MCP-Sum
      run: npx @anthropic-ai/dxt pack

    - name: Upload MCP-Sum Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcp-sum-dxt
        path: mcp-sum.dxt
